---
title: "Metrics of Succesful websites and companies"
author: "Danai Avratoglou"
date: "18 February 2017"
output:
  html_document: default
  pdf_document: default
---

```{r}
#we upload the dataset
total_500 <- read.csv("~/GitHub/thesis_msc_business_analytics/Python/total_500_new.csv", sep=";", na.strings="n/a")
#we see how many observations and how many variables we have
dim(total_500)
#We create a subset to make some changes to the data
total_500_sub <- total_500
#Change the decimal point for the 4 variables
total_500_sub$Assets.. <- gsub(",", ".", total_500_sub$Assets.. )
total_500_sub$Market.value.. <- gsub(",", ".", total_500_sub$Market.value.. )
total_500_sub$Revenues.. <- gsub(",", ".", total_500_sub$Revenues.. )
total_500_sub$Total.Stockholder.Equity.. <- gsub(",", ".", total_500_sub$Total.Stockholder.Equity.. )
#Make the variables numeric
for(i in 1:18){
 total_500_sub[,i] <- as.numeric(total_500_sub[,i])}  
for(i in 20:38){
 total_500_sub[,i] <- as.numeric(total_500_sub[,i])} 
#We omit the nas from the analysis
total_500_final <- na.omit(total_500_sub)
#We rename variable X as Ranking
colnames(total_500_final)[1] <- "Ranking"
#Change the names of some variables to be more easily readable
colnames(total_500_final)[2] <- "Assets"
colnames(total_500_final)[3] <- "Market_Value"
colnames(total_500_final)[4] <- "Revenues"
colnames(total_500_final)[5] <- "Total_SH_Equity"
colnames(total_500_final)[38] <- "Profit_per_Revenue"
#Delete the variables we will not need
total_500_final$company <- NULL #company name
total_500_final$url<- NULL # company url
#we upload the libraries beneath that we will use in the analysis
library(ggplot2)
library(reshape2)
library(DAAG)
#Final number of observation and variables we will use
dim(total_500_final)
#two of the variables were nas
```
```{r}
summary(total_500_final)
```

```{r}
#######################################################################################################
#we first see the summary of the Fortune variables and then we create their histogram so as to have a 
#good grasp of how they are distributed
plot(total_500_final$Ranking, col = "red")
ggplot(data=total_500_final,aes(x=Revenues))+geom_histogram(binwidth=10, colour = "green", fill ="darkgreen")
ggplot(data=total_500_final,aes(x=Assets))+geom_histogram(binwidth=80, colour = "red", fill ="darkred")
ggplot(data=total_500_final,aes(x=Market_Value))+geom_histogram(binwidth=90, colour = "blue", fill ="darkblue")
ggplot(data=total_500_final,aes(x=Total_SH_Equity))+geom_histogram(binwidth=100, colour = "purple", fill ="pink")
ggplot(data=total_500_final,aes(x=Profit_per_Revenue))+geom_histogram(binwidth=5, colour = "purple", fill ="pink")
```

```{r}
###############################################################################################
#We make plots to see how the variables we got from Fortune 500 are related with the Ranking
ggplot(total_500_final, aes(Assets,Ranking)) + geom_point(colour = "red")
ggplot(total_500_final, aes(Market_Value, Ranking)) + geom_point(colour = "blue")
ggplot(total_500_final, aes(Total_SH_Equity, Ranking)) + geom_point(colour = "purple")
ggplot(total_500_final, aes(Revenues, Ranking)) + geom_point(colour = "green")
ggplot(total_500_final, aes(Profit_per_Revenue, Ranking)) + geom_point(colour = "green")
#We can see that the Ranking has a linear relationship with the Revenues so we will use one of those 2 variables to check the relationships with the websites metrics
```
```{r}
#In order to see more clearly what type of relationship is there between the Revenues 
#and the Ranking we will create a variable where the gihest price would be of the most succesful companys
a = c(1:402)
for(i in 1:402){
  a[i] <- total_500_final$Ranking[403-i]
}
total_500_final$aRanking <- a
```

```{r}
###############################################################################################
#We make plots to see how the variables we got from Fortune 500 are related with the Ranking now
ggplot(total_500_final, aes(Assets,aRanking)) + geom_point(colour = "red")
ggplot(total_500_final, aes(Market_Value, aRanking)) + geom_point(colour = "blue")
ggplot(total_500_final, aes(Total_SH_Equity, aRanking)) + geom_point(colour = "purple")
ggplot(total_500_final, aes(Revenues, aRanking)) + geom_point(colour = "green")
ggplot(total_500_final, aes(Profit_per_Revenue, aRanking)) + geom_point(colour = "green")
#We can see that the Ranking has a linear relationship with the Revenues so we will use one of those 2 variables to check the relationships with the websites metrics
```

```{r}
#In order to have a more clear look we also create a correlation diagram
total_500_fortune <- total_500_final[,c(1:5,36)]
library(corrplot)
library(caret)
sm <- cor(total_500_fortune)
sm
corrplot(cor(total_500_fortune),method="number")
#From this plot we understand that the Ranking and the Revenues have very high correlation.
##########################################################################################################
```
```{r}
model_ranking_revenues <- lm(Ranking~1 +Revenues ,data=total_500_fortune)
summary(model_ranking_revenues)
```

```{r}
model_ranking_Profit_per_Revenue <- lm(Ranking~1 +Profit_per_Revenue ,data=total_500_fortune)
summary(model_ranking_Profit_per_Revenue)
```
```{r}
model_ranking_assets <- lm(Ranking~1 +Assets ,data=total_500_fortune)
summary(model_ranking_assets)
```

```{r}
model_ranking_market <- lm(Ranking~1 +Market_Value ,data=total_500_fortune)
summary(model_ranking_market)
```

```{r}
model_ranking_equity <- lm(Ranking~1 +Total_SH_Equity ,data=total_500_fortune)
summary(model_ranking_equity)
```
```{r}
model_ranking <- lm(Ranking~. ,data=total_500_fortune)
summary(model_ranking)
```

```{r}
#Firstly we will analyze the social media relevance with the sites.
#We will see how many of the sites have social media and what type of social media
#Facebook
social_media_facebook <- round(table(total_500_final$facebook)/402,3)
social_media_facebook
slicelable <- c(paste(35.6,"% no"),paste(64.4,"% yes"))
pie(social_media_facebook,label = slicelable,main="Share of companies with Facebook",col=rainbow(length(social_media_facebook)))
ggplot(total_500_final, aes(Revenues, facebook)) + geom_point(size=3, colour = "darkblue")

model_revenue_facebook <- lm(Revenues~1 +facebook ,data=total_500_final)
summary(model_revenue_facebook)
```

```{r}
#Twitter
social_media_twitter <- round(table(total_500_final$twitter)/402,3)
social_media_twitter
slicelable <- c(paste(31.3,"% no"),paste(68.7,"% yes"))
pie(social_media_twitter,label = slicelable,main="Share of companies with Twitter",col=rainbow(length(social_media_twitter)))
ggplot(total_500_final, aes(Revenues, twitter)) + geom_point(size=3, colour = "darkgreen")

model_revenue_twitter <- lm(Revenues~1 +twitter ,data=total_500_final)
summary(model_revenue_twitter)
```

```{r}
#Instagram
social_media_instagram <- round(table(total_500_final$instagram)/402,3)
social_media_instagram
slicelable <- c(paste(77.4,"% no"),paste(22.6,"% yes"))
pie(social_media_instagram,label = slicelable,main="Share of companies with Instagram",col=rainbow(length(social_media_instagram)))
ggplot(total_500_final, aes(Revenues, instagram)) + geom_point(size=3, colour = "pink")

model_revenue_instagram <- lm(Revenues~1 +instagram ,data=total_500_final)
summary(model_revenue_instagram)
```

```{r}
#Pinterest
social_media_pinterest <- round(table(total_500_final$pinterest)/402,3)
social_media_pinterest
slicelable <- c(paste(90.3,"% no"),paste(9.7,"% yes"))
pie(social_media_pinterest,label = slicelable,main="Share of companies with Pinterest",col=rainbow(length(social_media_pinterest)))
ggplot(total_500_final, aes(Revenues, pinterest)) + geom_point(size=3, colour = "darkred")

model_revenue_pinterest <- lm(Revenues~1 +pinterest ,data=total_500_final)
summary(model_revenue_pinterest)
```

```{r}
#Youtube
social_media_youtube <- round(table(total_500_final$youtube)/402,3)
social_media_youtube
slicelable <- c(paste(41.8,"% no"),paste(58.2,"% yes"))
pie(social_media_youtube,label = slicelable,main="Share of companies with Youtube",col=rainbow(length(social_media_youtube)))
ggplot(total_500_final, aes(Revenues, youtube)) + geom_point(size=3, colour = "red")

model_revenue_youtube <- lm(Revenues~1 +youtube ,data=total_500_final)
summary(model_revenue_youtube)
```

```{r}
#LinkedIn
social_media_linkedin <- round(table(total_500_final$linkedin)/402,3)
social_media_linkedin
slicelable <- c(paste(43.3,"% no"),paste(56.7,"% yes"))
pie(social_media_linkedin,label = slicelable,main="Share of companies with Linkedin",col=rainbow(length(social_media_linkedin)))
ggplot(total_500_final, aes(Revenues, linkedin)) + geom_point(size=3, colour = "blue")

model_revenue_linkedin <- lm(Revenues~1 +linkedin ,data=total_500_final)
summary(model_revenue_linkedin)
```

```{r}
#And we can also see for correlations
total_500_social_media <- total_500_final[,c(4,10:15)]
library(corrplot)
library(caret)
sm <- cor(total_500_social_media)
sm
corrplot(cor(total_500_social_media),method="number")
#we see that facebook has correlation more than 50% with twitter, youtube and linkedin
#And that the smallest correlations are those of pinterest and instagram

model_revenue_socialmedia <- lm(Revenues~. ,data=total_500_social_media)
summary(model_revenue_socialmedia)
#We see that the social media do not show any correlation with the revenues
#########################################################################################################
```

```{r}
#We will now check the links by creating an histogram
#Then we create ggplots in order to see in what frequency the links appear
par(mfrow=c(1,1))
library(ggplot2)
ggplot(data=total_500_final,aes(x=total.links))+geom_histogram(binwidth=50, colour = "darkblue", fill ="blue")
ggplot(total_500_final, aes(Revenues, total.links)) + geom_point(size=3, colour = "darkblue")
model_revenue_totallinks <- lm(Revenues~1 +total.links ,data=total_500_final)
summary(model_revenue_totallinks)
```

```{r}
ggplot(data=total_500_final,aes(x=external))+geom_histogram(binwidth=50, colour = "darkred", fill ="red")
ggplot(total_500_final, aes(Revenues, external)) + geom_point(size=3, colour = "darkred")
model_revenue_external <- lm(Revenues~1 +external ,data=total_500_final)
summary(model_revenue_external)
```

```{r}
ggplot(data=total_500_final,aes(x=internal))+geom_histogram(binwidth=50, colour = "darkgreen", fill ="green")
ggplot(total_500_final, aes(Revenues, internal)) + geom_point(size=3, colour = "darkgreen")
model_revenue_internal <- lm(Revenues~1 +internal ,data=total_500_final)
summary(model_revenue_internal)

```

```{r}
#And we can also see for correlations
total_500_links <- total_500_final[,c(4,21:23)]
library(corrplot)
library(caret)
tl <- cor(total_500_links)
tl
corrplot(cor(total_500_links),method="number")
#We can see that the total links with the internal links have a correlation almost 95%.
#So we will not include the total links in the regression model
model_revenue_links <- lm(Revenues~. ,data=total_500_links)
summary(model_revenue_links)
```

```{r}
#########################################################################################################
#Now we will see the loading time per site
ggplot(data=total_500_final,aes(x=loading.time))+geom_histogram(binwidth=1, colour = "pink", fill ="purple")
ggplot(total_500_final, aes(Revenues, loading.time)) + geom_point(size=3, colour = "purple")
model_revenue_loading.time <- lm(Revenues~1 +loading.time ,data=total_500_final)
summary(model_revenue_loading.time)
```

```{r}
#########################################################################################################
#Now we will see the total words, the unique words and the sentences how are distributed alone and in relationhsip with the revenues.
ggplot(data=total_500_final,aes(x=Sentences))+geom_histogram(binwidth=50, colour = "darkred", fill ="red")
ggplot(total_500_final, aes(Revenues, Sentences)) + geom_point(size=3, colour = "purple")
model_revenue_Sentences <- lm(Revenues~1 +Sentences ,data=total_500_final)
summary(model_revenue_Sentences)
```


```{r}
#########################
ggplot(data=total_500_final,aes(x=Unique.words))+geom_histogram(binwidth=50, colour = "darkred", fill ="red")
ggplot(total_500_final, aes(Revenues, Unique.words)) + geom_point(size=3, colour = "purple")
model_revenue_Unique.words <- lm(Revenues~1 +Unique.words ,data=total_500_final)
summary(model_revenue_Unique.words)
```


```{r}
#########################
ggplot(data=total_500_final,aes(x=Words))+geom_histogram(binwidth=50, colour = "darkred", fill ="red")
ggplot(total_500_final, aes(Revenues, Words)) + geom_point(size=3, colour = "purple")
model_revenue_Words <- lm(Revenues~1 +Words ,data=total_500_final)
summary(model_revenue_Words)
#############################
```


```{r}
#And we can also see for correlations
total_500_lt_w <- total_500_final[,c(4,18:20,34)]
library(corrplot)
library(caret)
tl <- cor(total_500_lt_w)
tl
corrplot(cor(total_500_lt_w),method="number")

model_revenue_lt_w <- lm(Revenues~. ,data=total_500_lt_w)
summary(model_revenue_lt_w)
```

```{r}
################################

#Next we will check the Flesh Measure alone and in relationship with revenues
ggplot(data=total_500_final,aes(x=Flesh_Mesaure))+geom_histogram(binwidth=50, colour = "darkred", fill ="red")
ggplot(total_500_final, aes(Revenues, Flesh_Mesaure)) + geom_point(size=3, colour = "purple")
model_revenue_Flesh_Mesaure <- lm(Revenues~1 +Flesh_Mesaure ,data=total_500_final)
summary(model_revenue_Flesh_Mesaure)
############################
```

```{r}
total_500_final$Readability <- gsub("Very easy", "01_VE", total_500_final$Readability )
total_500_final$Readability <- gsub("Easy", "02_E", total_500_final$Readability )
total_500_final$Readability <- gsub("Fairly easy", "03_FE", total_500_final$Readability )
total_500_final$Readability <- gsub("Standard", "04_St", total_500_final$Readability )
total_500_final$Readability <- gsub("Fairly difficult", "05_FD", total_500_final$Readability )
total_500_final$Readability <- gsub("Difficult", "06_D", total_500_final$Readability )
total_500_final$Readability <- gsub("Very Confusing", "07_VC", total_500_final$Readability )
barplot(table(total_500_final$Readability),col ="dark red")
```

```{r}
total_500_final$Readability <- gsub("01_VE","1", total_500_final$Readability )
total_500_final$Readability <- gsub("02_E", "2", total_500_final$Readability )
total_500_final$Readability <- gsub("03_FE", "3", total_500_final$Readability )
total_500_final$Readability <- gsub("04_St", "4", total_500_final$Readability )
total_500_final$Readability <- gsub("05_FD", "5", total_500_final$Readability )
total_500_final$Readability <- gsub("06_D", "6" ,total_500_final$Readability )
total_500_final$Readability <- gsub("07_VC", "7",total_500_final$Readability )
total_500_final$Readability <- as.numeric(total_500_final$Readability )
ggplot(data=total_500_final,aes(x=Readability))+geom_bar(binwidth=1, colour = "darkred", fill ="red")
ggplot(total_500_final, aes(Revenues, Readability)) + geom_point(size=3, colour = "purple")
model_revenue_Readability <- lm(Revenues~1 +Readability ,data=total_500_final)
summary(model_revenue_Readability)
```

```{r}
#And we can also see for correlations
total_500_r <- total_500_final[,c(4,16,17)]
library(corrplot)
library(caret)
tl <- cor(total_500_r)
tl
corrplot(cor(total_500_r),method="number")

model_revenue_r <- lm(Revenues~. ,data=total_500_r)
summary(model_revenue_r)
```


```{r}
#########################################################################################################
#Now we will see the number of errors and warnings alone and in relationship with the Revenues
ggplot(data=total_500_final,aes(x=number_of_errors))+geom_histogram(binwidth=50, colour = "red")
ggplot(total_500_final, aes(Revenues, number_of_errors)) + geom_point(size=3, colour = "dark red")
model_revenue_number_of_errors <- lm(Revenues~1 +number_of_errors ,data=total_500_final)
summary(model_revenue_number_of_errors)
```

```{r}
ggplot(data=total_500_final,aes(x=number_of_warning))+geom_histogram(binwidth=20, colour = "red")
ggplot(total_500_final, aes(Revenues, number_of_warning)) + geom_point(size=3, colour = "dark blue")
model_revenue_number_of_warning <- lm(Revenues~1 +number_of_warning ,data=total_500_final)
summary(model_revenue_number_of_warning)
```

```{r}
#Now we will see the non.document.error and the page not opened variables alone and in relationship with the Revenues
ggplot(data=total_500_final,aes(x=non.document.error))+geom_histogram(binwidth=1, colour = "red")
ggplot(total_500_final, aes(Revenues, non.document.error)) + geom_point(size=1, colour = "dark red")
model_revenue_non.document.error <- lm(Revenues~1 +non.document.error ,data=total_500_final)
summary(model_revenue_non.document.error)
```

```{r}
ggplot(data=total_500_final,aes(x=The_page_opened))+geom_histogram(binwidth=1, colour = "red")
ggplot(total_500_final, aes(Revenues, The_page_opened)) + geom_point(size=3, colour = "dark blue")
#In the page not opened we can see that the variable has only the price 1 that means that the page opened so there is no point in using it in the analysis as it does not affect the outcome
model_revenue_The_page_opened <- lm(Revenues~1 +The_page_opened ,data=total_500_final)
summary(model_revenue_The_page_opened)
```

```{r}
#And we can also see for correlations
total_500_html <- total_500_final[,c(4,7:9)]
library(corrplot)
library(caret)
tl <- cor(total_500_html)
tl
corrplot(cor(total_500_html),method="number")

model_revenue_html <- lm(Revenues~. ,data=total_500_html)
summary(model_revenue_html)
```

```{r}
#Now we will see the total images alone and in relationship with the revenues
ggplot(data=total_500_final,aes(x=total.images))+geom_histogram(binwidth=100, colour = "darkred", fill ="red")
ggplot(total_500_final, aes(Revenues, total.images)) + geom_point(size=3, colour = "dark blue")
model_revenue_total.images <- lm(Revenues~1 +total.images ,data=total_500_final)
summary(model_revenue_total.images)
```

```{r}
#Now we will see the total pixels of each webpage alone and in relationship with the revenues
ggplot(data=total_500_final,aes(x=pixels))+geom_histogram(binwidth=4000000, colour = "darkred", fill ="red")
ggplot(total_500_final, aes(Revenues, pixels)) + geom_point(size=3, colour = "dark blue")
model_revenue_pixels <- lm(Revenues~1 +pixels ,data=total_500_final)
summary(model_revenue_pixels)
```
```{r}
names(total_500_final)
```

```{r}
#########################################################################################################
#We will see now the frequency of image types that is being used

par(mfrow=c(1,1))
k = c(24:32)
for(i in 1:9){
  a <- k[i]
  image_type<- round(table(total_500_final[,a])/402,3)
  barplot(image_type,xlab=names(total_500_final)[a],ylab = "Shares of images per site", col = "dark green")}
```

```{r}
#It is obvious that the most common images type are .jpg, gif and .png
#We will check now the types in relationship with the revenues
ggplot(total_500_final, aes(Revenues, .bmp)) + geom_point(size=3, colour = "dark blue")
model_revenue_.bmp <- lm(Revenues~1 +.bmp ,data=total_500_final)
summary(model_revenue_.bmp)
```

```{r}
ggplot(total_500_final, aes(Revenues, .dib)) + geom_point(size=3, colour = "dark blue")
model_revenue_.dib <- lm(Revenues~1 +.dib ,data=total_500_final)
summary(model_revenue_.dib)
```

```{r}
ggplot(total_500_final, aes(Revenues, .gif)) + geom_point(size=3, colour = "dark blue")
model_revenue_.gif <- lm(Revenues~1 +.gif ,data=total_500_final)
summary(model_revenue_.gif)
```

```{r}
ggplot(total_500_final, aes(Revenues, .jpe)) + geom_point(size=3, colour = "dark blue")
model_revenue_.jpe <- lm(Revenues~1 +.jpe ,data=total_500_final)
summary(model_revenue_.jpe)
```

```{r}
ggplot(total_500_final, aes(Revenues, .jpeg)) + geom_point(size=3, colour = "dark blue")
model_revenue_.jpeg <- lm(Revenues~1 +.jpeg ,data=total_500_final)
summary(model_revenue_.jpeg)
```

```{r}
ggplot(total_500_final, aes(Revenues, .jpg)) + geom_point(size=3, colour = "dark blue")
model_revenue_.jpg <- lm(Revenues~1 +.jpg ,data=total_500_final)
summary(model_revenue_.jpg)
```

```{r}
ggplot(total_500_final, aes(Revenues, .png)) + geom_point(size=3, colour = "dark blue")
model_revenue_.png <- lm(Revenues~1 +.png ,data=total_500_final)
summary(model_revenue_.png)
```

```{r}
ggplot(total_500_final, aes(Revenues, .tif)) + geom_point(size=3, colour = "dark blue")
model_revenue_.tif <- lm(Revenues~1 +.tif ,data=total_500_final)
summary(model_revenue_.tif)
```

```{r}
ggplot(total_500_final, aes(Revenues, .tiff)) + geom_point(size=3, colour = "dark blue")
model_revenue_.tiff <- lm(Revenues~1 +.tiff ,data=total_500_final)
summary(model_revenue_.tiff)
```

```{r}
#And we can also see for correlations
total_500_im<- total_500_final[,c(4,24:32)]
library(corrplot)
library(caret)
tl <- cor(total_500_im)
tl
corrplot(cor(total_500_im),method="number")

model_revenue_im <- lm(Revenues~. ,data=total_500_im)
summary(model_revenue_im)
```



```{r}
#Now that we have analyzed each variable we will remove the other Fortune 500 variables since they will interfer in the outcome of the model and we keep only the variable we want to examine the Revenues
total_500_final_train <- total_500_final
total_500_final_train$Market_Value <- NULL
total_500_final_train$Assets <- NULL
total_500_final_train$Ranking <- NULL 
total_500_final_train$Total_SH_Equity <- NULL
total_500_final_train$The_page_opened <- NULL
total_500_final_train$aRanking <- NULL
total_500_final_train$Profit_per_Revenue <- NULL
total_500_final_train$total.links <- NULL
total_500_final_train$total.images <- NULL
```

```{r}
names(total_500_final_train)
```

```{r}
#We will now do a regression model with all the variables
library(caret)
library(glmnet)
#We create a full model for the variable Revenues
full_Revenues <- lm(Revenues~.,data=total_500_final_train)
summary(full_Revenues)
```

```{r}
#We will now try a new model but with a different dependent variable
total_500_final_train2 <- total_500_final
total_500_final_train2$Market_Value <- NULL
total_500_final_train2$Assets <- NULL
total_500_final_train2$Revenues <- NULL 
total_500_final_train2$Total_SH_Equity <- NULL
total_500_final_train2$The_page_opened <- NULL
total_500_final_train2$aRanking <- NULL
total_500_final_train2$Profit_per_Revenue <- NULL
total_500_final_train2$total.links <- NULL
total_500_final_train2$total.images <- NULL
```

```{r}
#We create a full model for the variable Revenues
full_Ranking <- lm(Ranking~.,data=total_500_final_train2)
summary(full_Ranking)
```
```{r}
#We will now try a new model but with a different dependent variable
total_500_final_train3 <- total_500_final
total_500_final_train3$Market_Value <- NULL
total_500_final_train3$Assets <- NULL
total_500_final_train3$Revenues <- NULL 
total_500_final_train3$Total_SH_Equity <- NULL
total_500_final_train3$The_page_opened <- NULL
total_500_final_train3$aRanking <- NULL
total_500_final_train3$Ranking <- NULL
total_500_final_train3$total.links <- NULL
total_500_final_train3$total.images <- NULL
```

```{r}
#We create a full model for the variable Profit_per_Revenue
full_Profit_per_Revenue <- lm(Profit_per_Revenue~.,data=total_500_final_train3)
summary(full_Profit_per_Revenue)
```
```{r}
#We will now try a new model but with a different dependent variable
total_500_final_train4 <- total_500_final
total_500_final_train4$Profit_per_Revenue <- NULL
total_500_final_train4$Assets <- NULL
total_500_final_train4$Revenues <- NULL 
total_500_final_train4$Total_SH_Equity <- NULL
total_500_final_train4$The_page_opened <- NULL
total_500_final_train4$aRanking <- NULL
total_500_final_train4$Ranking <- NULL
total_500_final_train4$total.links <- NULL
total_500_final_train4$total.images <- NULL
```

```{r}
#We create a full model for the variable Profit_per_Revenue
full_Market_Value <- lm(Market_Value~.,data=total_500_final_train4)
summary(full_Market_Value)
```

```{r}
#We will now try a new model but with a different dependent variable
total_500_final_train5 <- total_500_final
total_500_final_train5$Market_Value <- NULL
total_500_final_train5$Profit_per_Revenue <- NULL
total_500_final_train5$Revenues <- NULL 
total_500_final_train5$Total_SH_Equity <- NULL
total_500_final_train5$The_page_opened <- NULL
total_500_final_train5$aRanking <- NULL
total_500_final_train5$Ranking <- NULL
total_500_final_train5$total.links <- NULL
total_500_final_train5$total.images <- NULL
```

```{r}
#We create a full model for the variable Assets
full_Assets <- lm(Assets~.,data=total_500_final_train5)
summary(full_Assets)
```

```{r}
#We will now try a new model but with a different dependent variable
total_500_final_train3 <- total_500_final
total_500_final_train3$Market_Value <- NULL
total_500_final_train3$Assets <- NULL
total_500_final_train3$Revenues <- NULL 
total_500_final_train3$Profit_per_Revenue <- NULL
total_500_final_train3$The_page_opened <- NULL
total_500_final_train3$aRanking <- NULL
total_500_final_train3$Ranking <- NULL
total_500_final_train3$total.links <- NULL
total_500_final_train3$total.images <- NULL
```

```{r}
#We create a full model for the variable Total_SH_Equity
full_Total_SH_Equity <- lm(Total_SH_Equity~.,data=total_500_final_train3)
summary(full_Total_SH_Equity)
```


```{r}
#######################################################################################################
##################################################################################################
#Clustering 
#Kmeans clustering
#Based on those results we will try to cluster the companies based on the results of the regression
set.seed(220)
clusters <- hclust(dist(total_500_final))
plot(clusters)
```


```{r}
fortuneCluster <- kmeans(total_500_final, 10, iter.max = 500,nstart = 1)
cluster <- table(fortuneCluster$cluster)
fortuneCluster$cluster <- as.factor(fortuneCluster$cluster)

```


```{r}
ggplot(total_500_final, aes(pixels, pixels, color = fortuneCluster$cluster)) + geom_point(size=3)
#We create a full model for the variable pixels
full_pixels <- lm(pixels~.,data=total_500_final)
summary(full_pixels)
```

